# Generated by Django 5.0.6 on 2024-07-12 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True, null=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversation.conversation')),
            ],
        ),
    ]
