# Generated by Django 5.0.6 on 2024-06-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
