# Generated by Django 5.0.6 on 2024-06-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
