# Generated by Django 5.0.6 on 2024-06-18 14:28

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(null=True, upload_to=user.models.get_user_path),
        ),
    ]
